### ISSUE TITLE
Coin change bottom up bug

### ISSUE THREAD

**Issue by 8ahmadreza3** [RezaAmirzadehFard/Algorithms#2]
In this algorithm, j must be equal to m **( j<=m )** and the condition for checking that the value of the coin is greater than the total value must be **( coins[ i ] > j )**.

  ```
static int changeMakingBU(int[] coins, int n, int m) {
    int[][] r = new int[n + 1][m + 1] ;
    for (int j=1 ; j<=m ; ++j) {
      r[0][j] = Integer.MAX_VALUE ;
      for (int i=1 ; i<=n ; ++i) {
        r[i][0] = 0 ;
        if (coins[i] > j) {
          r[i][j] = r[i - 1][j] ;
        } else {
          int q = r[i-1][j] ;
          int p = r[i][j-coins[i]] + 1 ;
          r[i][j] = Math.min(q, p);
        }
      }
    }
    return r[n][m] ;
  }
```

**Comment by RezaAmirzadehFard** [comment]
You are correct and I agree with you, this bug was happened because I wasn't write a testcase for my function. I really appreciate the care that you took to check the details. Thanks for your precision.

**Comment by RezaAmirzadehFard** [comment]
You are correct and I agree with you, this bug was happened because I wasn't write a testcase for my function. I really appreciate the care that you took to check the details. Thanks for your precision.
